### PR TITLE
Update README.md to reflect valid PHP version

### LINKED ISSUE #145: Update README.md to reflect valid PHP versions
## What happened?

README.md has the wrong PHP version on the example shown ( 10.x )

* What were you attempting to do?
I was about to send a PR but I wanted to create the issue first.

* What did you expect to happen?
Update the file

* What was the actual behavior? Please provide log output, if possible.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

* What buildpacks are you using? Please include versions.

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

### PR DESCRIPTION
**Pull request by oscarnevarezleal**
Update contents of the file to reflect valid PHP versions, Fixes #145 

## Summary
No-ops change, just an update on the docs.

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.

### CODE REVIEW

**Comment by arjun024** [comment]
@oscarnevarezleal You have to sign and submitted the Contributor License Agreement. There's a CLA bot but it doesn't seem to work on a few repos including this one. Can you take a look at https://github.com/paketo-buildpacks/.github/blob/main/CONTRIBUTING.md#how-do-i-become-a-contributor?

**Comment by arjun024** [comment]
Yay CLA ;-)
@oscarnevarezleal You should be able to follow the above link

**Comment by oscarnevarezleal** [comment]
Thank you @arjun024.
I've signed the CLA.

**Comment by arjun024** [comment]
Thanks

**Review by arjun024 — APPROVED** [review]

**Pull request merged**
