### PR TITLE
Refactor README

### PR DESCRIPTION
**Pull request by arjun024**
- Removed `php-script` details as it looks outdated

[#171770870]

Co-authored-by: Arjun Sreedharan <asreedharan@pivotal.io>

cc @ForestEckhardt

### CODE REVIEW

**Comment by arjun024** [comment]
@dmikusa-pivotal

**Comment by arjun024** [comment]
@dmikusa-pivotal 
2. The intention is to say:
(a) Since PHP Web cnb provides `php-web` as dependency, nothing stops a downstream cnb from technically requiring them.
(b) In the recommended workflow, this would be only used as the last cnb in an ordered chain of cnbs.
(c) If a user likes to include some other functionality (say a performance monitoring tool or a db driver), it can be done independent of the PHP Web cnb without requiring a dependency of it.

--

Does this sound right? If so, we can spell it out.
Also looping in @ForestEckhardt

**Comment by dmikusa-pivotal** [comment]
Got it. Maybe just spell it out in a list like you have here?

>(a) Since PHP Web cnb provides php-web as dependency, nothing stops a downstream cnb from technically requiring them.

I can't imagine a case where it would be necessary to require the php-web cnb. I would suggest adding a qualifier like "but you should almost never need to do this".

>(b) In the recommended workflow, this would be only used as the last cnb in an ordered chain of cnbs.

I don't think it needs to be last globally, just last in the standard chain of PHP CNBs. You can very easily add on additional CNBs after php-web. The APM buildpacks we tested were added after it & they seem to work just fine.

>(c) If a user likes to include some other functionality (say a performance monitoring tool or a db driver), it can be done independent of the PHP Web cnb without requiring a dependency of it.

I think this is the main point to make. To discourage people from forking/modifying this CNB to add functionality.

**Comment by arjun024** [comment]
@dmikusa-pivotal rewrote the paragraph

**Pull request merged**
